name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Menjalankan setiap hari pada pukul 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: rizkiramadhan12121
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Automated commit by GitHub Actions" || exit 0
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/rizkiramadhan12121/rizkiramadhan12121.git main
